# Generated by Django 3.2.2 on 2021-05-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0004_auto_20210529_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='creativity',
            new_name='content',
        ),
    ]
